apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader-dex-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-dex-rolebinding
  namespace: default
subjects:
- kind: User
  name: user@domain.com
  namespace: default
roleRef:
  kind: Role
  name: service-reader-dex-role
  apiGroup: rbac.authorization.k8s.io
